# Generated by Django 3.0.8 on 2020-07-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='potfolio_site',
            new_name='portfolio_site',
        ),
    ]
